---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.50.0

#! Rebase rules explicitly define how kapp should merge resources during an update.
#! See more about the resource merge method: https://carvel.dev/kapp/docs/latest/merge-method.
rebaseRules:

#! Some Secrets are created empty and populated at install time by Dapr with TLS certificates.
#! We prefer the manifest configuration, but allow the one set on the cluster.
- paths:
  - [data, ca.crt]
  - [data, issuer.crt]
  - [data, issuer.key]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: Secret, name: dapr-trust-bundle}

#! Some ConfigMaps are created empty and populated at install time by Dapr with TLS certificates.
#! We prefer the manifest configuration, but allow the one set on the cluster.
- paths:
  - [data, ca.crt]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap, name: dapr-trust-bundle}

#! This webhook configuration is manipulated at install time by Dapr.
#! We want to persist those changes between upgrades.
- paths:
  - [spec, conversion, webhook, clientConfig, service, namespace]
  - [spec, conversion, webhook, clientConfig, service, port]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: apiextensions.k8s.io/v1, kind: CustomResourceDefinition}
